services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    env_file: .env
    ports:
      - '${REDIS_PORT}:6379'
    command:
      - redis-server
      - '--port'
      - '${REDIS_PORT}'
      - '--requirepass'
      - '${REDIS_PASSWORD}'
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
